blog/urls.py
from blog.views import about, delete_blog, edit_blog, home, create_blog, view_blog
from django.urls import path

app_name = "blog"

urlpatterns = [
    path('', home, name='index'),
    path('about/', about, name='about'),
    path('create/', create_blog, name='create_blog'),
    path('<blog_id>/', view_blog, name='view_blog'),
    path('edit/<blog_id>/', edit_blog, name='edit_blog'),
    path('delete/<blog_id>/', delete_blog, name='delete_blog'),
]

url_shorner/urls.py
from django.urls import path

from url_shorner.views import home, delete_url, redirect_to_url

app_name = "url_shorner"

urlpatterns = [
    path('', home, name='index'),
    path('<str:uid>/', redirect_to_url, name='redirect_to_url'),
    path('delete/<str:uid>/', delete_url, name='delete_url'),
]

url_shorner/models.py
from django.db import models
from uuid import uuid4

# Create your models here.

def generate_unique_id():
    return str(uuid4())[:5]


class Url(models.Model):
    url = models.URLField()
    uid = models.CharField(max_length=5, unique=True,
                           primary_key=True, default=generate_unique_id, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.uid} - {self.url}"

url_shorner/forms.py
from django import forms

from url_shorner.models import Url


class UrlShortenerForm(forms.ModelForm):

    class Meta:
        model = Url
        fields = ['url']
        widgets = {
            'url': forms.TextInput(attrs={
                'placeholder': 'Enter URL here',
                'class': 'form-control'
            })
        }
        labels = {
            'url': 'Enter URL'
        }
        error_messages = {
            'url': {
                'required': 'This field is required.',
                'invalid': 'Please enter a valid URL.'
            }
        }
        help_texts = {
            'url': 'Please enter a valid URL.'
        }

url_shorner/views.py
from django.shortcuts import get_object_or_404, redirect, render

from url_shorner.forms import UrlShortenerForm
from url_shorner.models import Url
from django.contrib import messages

# Create your views here.

from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    from django.db.models import Value
    all_urls = Url.objects.all()
    # .annotate(
    #     short_url=Value(f"{request.build_absolute_uri('/shortner/uid/')}",
    # )
    messages.success(request, 'This is a success message.')
    messages.error(request, 'An error occurred.')
    messages.warning(request, 'This is a warning.')
    messages.info(request, 'Just an informational message.')
    form = UrlShortenerForm()

    context = {
        "urls": all_urls,
        "myform": form,
    }

    if request.method == "POST":
        form = UrlShortenerForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New Item created.')
            return render(request, "url_shorner/index.html", context)

    return render(request, "url_shorner/index.html", context)


def delete_url(request, uid):
    url = Url.objects.get(uid=uid)
    url.delete()
    return redirect("url_shorner:index")


def redirect_to_url(request, uid):
    # url = Url.objects.get(uid=uid)
    url = get_object_or_404(Url, uid=uid)
    # Redirect to a specific URL

    return redirect(url.url)

templates/url_shorner/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Url Shortner</title>
  </head>
  <body>
    <header>
      <h1>Url Shortner</h1>
    </header>
    <main>
      <form action="{% url 'url_shorner:index' %}" method="post">
        {% csrf_token %} {{ myform.as_p }} {{ myform.non_field_errors }}

        <button type="submit">Shorten URL</button>
      </form>

      <h2>All Urls</h2>

      {{ messages }} {% if messages %}
      <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}

      <ul>
        {% for url in urls %}
        <li>
          <a
            href="{% url 'url_shorner:redirect_to_url' url.uid %}"
            target="_blank"
          >
            {{request.scheme }}://{{request.get_host}}/shortner/{{ url.uid }}
          </a>
          <br />
          - {{ url.short_url }}
          <form
            action="{% url 'url_shorner:delete_url' url.pk %}"
            method="post"
          >
            {% csrf_token %}
            <button
              onclick="alert('Aare you sure you want to delete?')"
              type="submit"
            >
              Delete
            </button>
          </form>
        </li>
        <hr />
        <hr />
        {% endfor %}
      </ul>
    </main>
    <footer>
      <p>&copy; 2023 Your Company Name. All rights reserved.</p>
      <p>
        <a href="/about">About Us</a> | <a href="/contact">Contact</a> |
        <a href="/privacy-policy">Privacy Policy</a>
      </p>
    </footer>
  </body>
</html>